
#include <cuda_runtime.h>

#define BLOCK_DIM 32

// Diagnoal Factorization Kernel
// A11 = L11L11^T --> L11 = cholesky(A11)
// 3 steps:
// 1. sqrt(Akk)
// 2. column update Aik /= Akk, where i > k
// 3. Trailing matrix subtract Aij -= Aik * Akj, lower triangle, j > k, i >= j
__global__ void diagnoal_factorization_kernel(float* d_A, int n, int k_block) {

    __shared__ float tile_A[BLOCK_DIM][BLOCK_DIM + 1];

    int tx = threadIdx.x;
    int ty = threadIdx.y;
    int row_offset = k_block * BLOCK_DIM;
    int col_offset = k_block * BLOCK_DIM;
    int global_row_idx = row_offset + ty;
    int global_col_idx = col_offset + tx;

    // load from global memory to shared tiling memory
    if (global_row_idx < n && global_col_idx < n) {
        tile_A[ty][tx] = d_A[global_row_idx * n + global_col_idx];
    }
    else {
        tile_A[ty][tx] = 0.0f;
    }
    __syncthreads();

    for (int k = 0; k < BLOCK_DIM; k++) {
        // step 1: sqrt diagonal
        if (ty == k && tx == k) {
            tile_A[k][k] = sqrtf(tile_A[k][k]);
        }
        __syncthreads();

        // step 2: update Column
        if (tx == k && ty > k) {
            tile_A[ty][k] /= tile_A[k][k];
        }
        __syncthreads();

        // step 3: trailing matrix subtract
        if (tx > k && ty >= tx) {
            // Aij -= Aik Akj, j > k, i >= j for the trailing matrix
            // however, this kernel only updates the lower triangle, Akj might still has original A value
            // need to flip the index and read Ajk instead, since it's symmetric
            tile_A[ty][tx] -= tile_A[ty][k] * tile_A[tx][k];
        }
        __syncthreads();
    }

    // write the factorized lower triangle tile to the global memory
    // lower triangle part (ty >= tx)
    if (global_row_idx < n && global_col_idx < n && ty >= tx) {
        d_A[global_row_idx * n + global_col_idx] = tile_A[ty][tx];
    }
    // upper triangle part (ty < tx), if want to preserve the original upper of A, skip this else if
    else if (global_row_idx < n && global_col_idx < n && ty < tx) {
        d_A[global_row_idx * n + global_col_idx] = 0.0f;
    }
}

#include <iostream>
#include <vector>
#include <cmath>
#include <cassert>

// CPU in place diagonal factorization (row-majored)
// Clean out the upper triangle to match the gpu kernel
void diagonal_factorizer_cpu(float* A, int n) {
    for (int k = 0; k < n; k++) {
        float val = A[k * n + k];
        assert(val > 0.0f && "Assert failure: A is not positive definite!");
        // Compute diagonal sqrt
        A[k * n + k] = std::sqrt(val);
        
        // update column below k
        for (int i = k + 1; i < n; i++) {
            A[i * n + k] /= A[k * n + k];
        }

        // Trailing matrix subtract
        for (int j = k + 1; j < n; j++) {
            for (int i = j; i < n; i++) { // ensure i >= j for lower triangle
                A[i * n + j] -= A[i * n + k] * A[j * n + k];
            }
        }
    }

    // clean out the upper triangle part (ty < tx) if the kernel does so
    for (int i = 0; i < n; i++) {
      for (int j = i + 1; j < n; j++) {
          A[i * n + j] = 0.0f;
      }
    }
}

#define CHECK_CUDA(call) { \
    cudaError_t err = call; \
    if (err != cudaSuccess) { \
        printf("Error: %s in %s at %d!", cudaGetErrorString(err), __FILE__, __LINE__); \
        exit(EXIT_FAILURE); \
    } \
}

int main() {

    const int N = 4;
    const size_t bytes = N * N * sizeof(float);

    // Hardcode a 4x4 positive-definite A
    // Generated by random lower triangle L, then A = L L^T
    float h_A_cpu[N * N] = {
         4.0f,   12.0f,  -16.0f,  4.0f,
        12.0f,   37.0f,  -43.0f, 13.0f,
       -16.0f,  -43.0f,   98.0f, -9.0f,
         4.0f,   13.0f,   -9.0f, 33.0f
    };

    // Copy the initial A cpu to gpu
    float h_A_gpu[N * N];
    for (int i = 0; i < N * N; i++) {
        h_A_gpu[i] = h_A_cpu[i];
    }

    // Diagonal factorize cpu A
    diagonal_factorizer_cpu(h_A_cpu, N);

    // Host memory to device
    float* d_A = nullptr;
    CHECK_CUDA(cudaMalloc((void**)&d_A, bytes));
    CHECK_CUDA(cudaMemcpy(d_A, h_A_gpu, bytes, cudaMemcpyHostToDevice));

    // diagonal factoriaztion kernel call
    // kernel config: 1 block of BLOCK_DIM x BLOCK_DIM
    dim3 ThreadsPerBlock(BLOCK_DIM, BLOCK_DIM);
    dim3 BlocksPerGrid(1, 1);

    // launch k_block = 0 (step 0) for the diagonal factorization
    diagnoal_factorization_kernel<<<BlocksPerGrid, ThreadsPerBlock>>>(d_A, N, 0);

    // sync and copy result back to the host memory
    cudaDeviceSynchronize();
    CHECK_CUDA(cudaMemcpy(h_A_gpu, d_A, bytes, cudaMemcpyDeviceToHost));

    // Verify by comparing cpu result vs gpu result
    bool isSuccess = true;
    const float epsilon = 1e-5f;
    for (int i = 0; i < N * N; i++) {
      if (std::abs(h_A_cpu[i] - h_A_gpu[i]) > epsilon) {
          isSuccess = false;
          std::cout << "Error at row " << i / N << " column " << i % N
                    << " ! Expecting " << h_A_cpu[i] << " but got " << h_A_gpu[i] << std::endl;
          break;
      }
    }
    std::cout << "Verification isSuccess: " << isSuccess << std::endl;

    cudaFree(d_A);
    return 0;
}
