"""
ExtractNsightReportMetrics.py
-----------------------------
Parses NVIDIA Nsight Compute ncu raw-metric-dump CSV files (the format
generated by `ncu --csv --print-details all ./kernel`) into small,
committable summary CSVs -- kilobytes instead of megabytes.

Supports TWO formats automatically:
  Format A (benchmarks/): the ncu raw-metric-dump format.
    Each kernel is a separate block:
      Line 1: "[PID] process@host"      <- process header, skip
      Line 2: "  kernelName(...) (G)x(B), Context N, Stream N, ..."  <- kernel block start
      Lines 3+: "  metric_name   unit   value"  <- one metric per line
    Example first column: "[7265] cholesky_tiled@127.0.0.1"

  Format B (numerical-solvers/profile/): the ncu tabular export format.
    A real CSV table with "Kernel Name", "Metric Name", "Metric Value"
    or wide format with one column per metric.
    Example first column: "ID" or "Kernel Name"

Usage:
  Run from the repo root (cuda-kernel-acceleration/):
    python3 ExtractNsightReportMetrics.py

  Writes *_summary.csv alongside each *_report.csv found recursively.
  Add the summary CSVs to git -- they are small enough to commit.
"""

import re
import os
import csv
import glob
from collections import defaultdict

KEY_METRICS = [
    'gpu__time_duration.sum',
    'gpu__time_duration.avg',
    'sm__throughput.avg.pct_of_peak_sustained_elapsed',
    'gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed',
    'dram__throughput.avg.pct_of_peak_sustained_elapsed',
    'sm__warps_active.avg.pct_of_peak_sustained_active',
    'launch__occupancy_limit_blocks',
    'launch__occupancy_limit_registers',
    'launch__occupancy_limit_shared_mem',
    'launch__occupancy_limit_warps',
    'launch__registers_per_thread',
    'sm__sass_thread_inst_executed_op_ffma_pred_on.sum',
    'dram__bytes.sum',
    'l1tex__t_bytes_pipe_lsu_mem_global_op_ld.sum',
    'l1tex__t_bytes_pipe_lsu_mem_global_op_st.sum',
]


def detect_format(filepath):
    """
    Return 'A' (raw metric dump) or 'B' (tabular CSV).
    Format A: first non-empty line starts with '[' (process header).
    Format B: first non-empty line starts with a real CSV header
              containing 'ID', 'Kernel Name', or 'Kernel'.
    """
    with open(filepath, encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith('['):
                return 'A'
            # Check for tabular CSV header markers
            if any(marker in line for marker in
                   ['"ID"', 'Kernel Name', '"Kernel"', 'Process ID']):
                return 'B'
            return 'A'  # default to A if ambiguous
    return 'A'


def parse_format_a(filepath):
    """
    Parse ncu raw-metric-dump format (one metric per line per kernel block).
    Returns a list of dicts: [{'kernel': name, metric: value, ...}, ...]
    """
    kernels = []
    current_kernel = None
    current_metrics = {}

    # Regex: kernel block header -- 2 leading spaces, then
    # "kernelFunctionName(args) (Gx,Gy,Gz)x(Bx,By,Bz), ..."
    kernel_line_re = re.compile(r'^  \S.*\(.*\)x\(.*\)')

    with open(filepath, encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.rstrip()

            if kernel_line_re.match(line):
                # Save previous kernel before starting new one
                if current_kernel is not None:
                    kernels.append({'kernel': current_kernel, **current_metrics})
                # Extract just the function name (before the first '(')
                current_kernel = line.strip().split('(')[0].strip()
                current_metrics = {}

            elif (line.startswith('[') or             # process header
                  line.startswith('  Metric Name') or # column header row
                  line.startswith('  ---')):           # separator row
                continue

            elif line.startswith('  ') and line.strip():
                # Metric value line: "  metric_name   unit   value"
                parts = line.strip().split()
                if len(parts) >= 2:
                    metric_name = parts[0]
                    value_str = parts[-1].replace(',', '')
                    if metric_name in KEY_METRICS:
                        try:
                            current_metrics[metric_name] = float(value_str)
                        except ValueError:
                            current_metrics[metric_name] = value_str

    # Don't forget the last kernel block
    if current_kernel is not None:
        kernels.append({'kernel': current_kernel, **current_metrics})

    return kernels


def parse_format_b(filepath):
    """
    Parse ncu tabular CSV export format (wide: one column per metric).
    Returns a list of dicts: [{'kernel': name, metric: value, ...}, ...]
    """
    # Find the actual header row -- it contains 'Kernel Name' or 'ID'
    header_row_idx = 0
    with open(filepath, encoding='utf-8', errors='replace') as f:
        for i, line in enumerate(f):
            if any(m in line for m in ['Kernel Name', '"ID"', '"Kernel"']):
                header_row_idx = i
                break

    try:
        import pandas as pd
        df = pd.read_csv(
            filepath,
            skiprows=header_row_idx,
            low_memory=False,
            encoding='utf-8',
            on_bad_lines='skip',
        )
    except ImportError:
        # Fallback without pandas
        with open(filepath, encoding='utf-8', errors='replace') as f:
            lines = f.readlines()
        header = [c.strip().strip('"') for c in lines[header_row_idx].split(',')]
        rows = []
        for line in lines[header_row_idx + 1:]:
            vals = line.strip().split(',')
            rows.append(dict(zip(header, vals)))
        df_data = rows
        # Convert to list of dicts with just the fields we need
        kernel_col = next((h for h in header
                           if h in ['Kernel Name', 'Kernel', 'Name']), None)
        if kernel_col is None:
            return []
        result = []
        for row in df_data:
            entry = {'kernel': str(row.get(kernel_col, '')).strip()}
            for m in KEY_METRICS:
                val = row.get(m, '')
                try:
                    entry[m] = float(str(val).replace(',', '').strip())
                except ValueError:
                    entry[m] = None
            result.append(entry)
        return result

    # pandas path
    df.columns = [c.strip().strip('"') for c in df.columns]
    kernel_col = next((c for c in df.columns
                       if c in ['Kernel Name', 'Kernel', 'Name']), None)
    if kernel_col is None:
        return []

    result = []
    for _, row in df.iterrows():
        kname = str(row[kernel_col]).strip()
        if not kname or kname in ('nan', 'Kernel Name', 'Kernel'):
            continue
        entry = {'kernel': kname}
        for m in KEY_METRICS:
            if m in df.columns:
                val = row[m]
                if isinstance(val, str):
                    val = val.strip().rstrip('%').replace(',', '')
                    try:
                        val = float(val)
                    except ValueError:
                        val = None
                entry[m] = val
            else:
                entry[m] = None
        result.append(entry)
    return result


def write_summary(kernels, out_path):
    """Write extracted metrics to a small summary CSV."""
    fieldnames = ['kernel'] + KEY_METRICS
    with open(out_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        writer.writeheader()
        for k in kernels:
            # Fill missing metrics with empty string
            row = {m: k.get(m, '') for m in fieldnames}
            writer.writerow(row)


def main():
    report_csvs = sorted(glob.glob('**/*_report.csv', recursive=True))
    if not report_csvs:
        print("No *_report.csv files found. Run from the repo root "
              "(cuda-kernel-acceleration/).")
        return

    for csv_path in report_csvs:
        fmt = detect_format(csv_path)
        print(f"Processing [{fmt}]: {csv_path}")

        kernels = parse_format_a(csv_path) if fmt == 'A' else parse_format_b(csv_path)

        if not kernels:
            print(f"  SKIP: no kernel rows extracted.")
            continue

        out_path = csv_path.replace('_report.csv', '_summary.csv')
        write_summary(kernels, out_path)

        size_kb = os.path.getsize(out_path) / 1024
        print(f"  Written: {out_path} ({size_kb:.1f} KB, {len(kernels)} rows)")

    print("\nDone. Commit the *_summary.csv files to your repo.")


if __name__ == '__main__':
    main()
